io:
  dir_scene_graph: /mnt/ebs_xizhn5/Coohom/Data/rooms/scene_graph
  resume_from:
  logdir: logs/
params:
  img_height: 1024
  img_width: 1024
  nworkers: 1
training_params:
  train_ratio: 0.8
  n_epochs: 200
  batch_size: 1
  lr: 0.001
  amsgrad: True
  weight_decay: 4.0e-2
  optimizer: Adam
  lr_decay_epoch: 30
  n_val_imgs: 16